name: Docker Image CI

on:
  push:
    paths:
      - Dockerfile
      - assets/build.sh
  workflow_dispatch:

env:
  IMAGE_NAME: willb97/pyapriltags

jobs:
  build-image:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
        fetch-depth: 0
        fetch-tags: true
    - name: Generate release version
      id: release_version
      run: |
        echo "WHEEL_VERSION=ghcr.io/$IMAGE_NAME:$(git describe --tags --always),ghcr.io/$IMAGE_NAME:latest" >> "$GITHUB_OUTPUT"
    - name: 'Login to GitHub Container Registry'
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{github.actor}}
        password: ${{secrets.GITHUB_TOKEN}}
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ghcr.io/${{ env.IMAGE_NAME }}
    - name: Build and push Docker image
      id: push
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: ${{ steps.release_version.outputs.WHEEL_VERSION }}
        labels: ${{ steps.meta.outputs.labels }}
